### ISSUE TITLE
set duration and start from another time

### ISSUE THREAD

**Issue by alirezat66** [smladeoye/flutter-simple-timer#1]
how can set duration for example 30 s , then start from 20 second?
I want use a button to add some time to my countdown timer. 
for example I start with 45 and then, when I am in 20 second remind, I add 15 second, So duration should be 45 and remind time should be 35, how can do this. thanks for your reply.

**Comment by smladeoye** [comment]
Hi, a new update has been made to make this more convenient. You can now call the **add or subtract method of the TimerController**. In your case you simply call the add method like below:

**_timerController.add(Duration(seconds: 15))**
